### ISSUE TITLE
猫狗特征询问

### ISSUE THREAD

**Issue by Kenneth-X** [KuHung/DateCastle#1]
请问
dogs=[251, 268, 256, 253, 255, 254, 257, 159, 211, 210, 212, 214, 213, 216, 215, 219, 220, 221, 217, 218, 207, 209, 206, 205, 208, 193, 202, 194, 191, 204, 187, 203, 185, 192, 183, 199, 195, 181, 184, 201, 186, 200, 182, 188, 189, 190, 197, 196, 198, 179, 180, 177, 178, 175, 163, 174, 176, 160, 162, 161, 164, 168, 173, 170, 169, 165, 166, 167, 172, 171, 264, 263, 266, 265, 267, 262, 246, 242, 243, 248, 247, 229, 233, 234, 228, 231, 232, 230, 227, 226, 235, 225, 224, 223, 222, 236, 252, 237, 250, 249, 241, 239, 238, 240, 244, 245, 259, 261, 260, 258, 154, 153, 158, 152, 155, 151, 157, 156]

cats=[281,282,283,284,285,286,287]
这个特征向量是怎么来的呢？

**Comment by kuhung** [comment]
还记得我们导入的那个权重模型吗？这些数是模型中预训练得出的属于猫狗的特征向量。

**Comment by Kenneth-X** [comment]
哦哦。训练过程你这里没写，只有测试对吧。

**Comment by kuhung** [comment]
对，用的训练好的模型。
